# Generated by Django 6.0.7 on 2026-08-17 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1200, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_p1', to='players.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_p2', to='players.player')),
            ],
        ),
    ]
