# Generated by Django 6.0.7 on 2026-08-18 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_rating_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='initial_rating',
            field=models.IntegerField(default=1200, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rating_changes', to='players.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_history', to='players.player')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
