# Generated by Django 6.0.7 on 2026-08-18 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_initial_rating_ratinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score1__gte', 0), ('score2__gte', 0)), name='match_scores_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('player1', models.F('player2')), _negated=True), name='match_players_distinct'),
        ),
    ]
