# Generated by Django 6.0.7 on 2026-08-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_match_score1_alter_match_score2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='date'),
        ),
    ]
