# Generated by Django 6.0.7 on 2026-08-18 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinghistory',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to='players.match'),
        ),
    ]
