# Generated by Django 6.0.7 on 2026-08-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_ratinghistory_match'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('player1', 'player2', 'score1', 'score2', 'date'), name='prevent_identical_match_duplicates', violation_error_message='This identical match has already been logged.'),
        ),
        migrations.AlterConstraint(
            model_name='match',
            name='match_players_distinct',
            constraint=models.CheckConstraint(condition=models.Q(('player1', models.F('player2')), _negated=True), name='match_players_distinct', violation_error_message='A player cannot play a match against themselves.'),
        ),
    ]
