# Generated by Django 6.0.7 on 2026-08-23 04:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_match_prevent_identical_match_duplicates_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('score1', models.F('score2')), _negated=True), name='match_scores_not_tied', violation_error_message='One player must win.'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_player_name_ci', violation_error_message='A player with this name already exists.'),
        ),
    ]
